# Form implementation generated from reading ui file 'src/views/network/http/requests_table.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RequestsTable(object):
    def setupUi(self, RequestsTable):
        RequestsTable.setObjectName("RequestsTable")
        RequestsTable.resize(509, 702)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RequestsTable.sizePolicy().hasHeightForWidth())
        RequestsTable.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(RequestsTable)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.siteMapButton = QtWidgets.QPushButton(RequestsTable)
        self.siteMapButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.siteMapButton.setObjectName("siteMapButton")
        self.horizontalLayout_2.addWidget(self.siteMapButton)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchBox = QtWidgets.QLineEdit(RequestsTable)
        self.searchBox.setObjectName("searchBox")
        self.verticalLayout_2.addWidget(self.searchBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.displayFiltersButton = QtWidgets.QPushButton(RequestsTable)
        self.displayFiltersButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.displayFiltersButton.setMinimumSize(QtCore.QSize(75, 16777215))
        self.displayFiltersButton.setObjectName("displayFiltersButton")
        self.horizontalLayout.addWidget(self.displayFiltersButton)
        self.captureFiltersButton = QtWidgets.QPushButton(RequestsTable)
        self.captureFiltersButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.captureFiltersButton.setMinimumSize(QtCore.QSize(75, 16777215))
        self.captureFiltersButton.setObjectName("captureFiltersButton")
        self.horizontalLayout.addWidget(self.captureFiltersButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.requestsTable = HoverableQTableView(RequestsTable)
        self.requestsTable.setObjectName("requestsTable")
        self.verticalLayout_3.addWidget(self.requestsTable)

        self.retranslateUi(RequestsTable)
        QtCore.QMetaObject.connectSlotsByName(RequestsTable)

    def retranslateUi(self, RequestsTable):
        _translate = QtCore.QCoreApplication.translate
        RequestsTable.setWindowTitle(_translate("RequestsTable", "Form"))
        self.searchBox.setPlaceholderText(_translate("RequestsTable", "Press enter to search"))
        self.displayFiltersButton.setText(_translate("RequestsTable", "Display"))
        self.captureFiltersButton.setText(_translate("RequestsTable", "Capture"))
from widgets.qt.hoverable_q_table_view import HoverableQTableView
