# Form implementation generated from reading ui file 'src/ui/views/shared/code_editor.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CodeEditor(object):
    def setupUi(self, CodeEditor):
        CodeEditor.setObjectName("CodeEditor")
        CodeEditor.resize(880, 521)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(CodeEditor)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.findReplace = QtWidgets.QWidget(CodeEditor)
        self.findReplace.setObjectName("findReplace")
        self.findReplaceLayout = QtWidgets.QHBoxLayout(self.findReplace)
        self.findReplaceLayout.setObjectName("findReplaceLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.findReplaceLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.findText = QtWidgets.QLineEdit(self.findReplace)
        self.findText.setMinimumSize(QtCore.QSize(200, 0))
        self.findText.setObjectName("findText")
        self.horizontalLayout_2.addWidget(self.findText)
        self.findButton = QtWidgets.QPushButton(self.findReplace)
        self.findButton.setObjectName("findButton")
        self.horizontalLayout_2.addWidget(self.findButton)
        self.findPrevButton = QtWidgets.QPushButton(self.findReplace)
        self.findPrevButton.setObjectName("findPrevButton")
        self.horizontalLayout_2.addWidget(self.findPrevButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.replaceText = QtWidgets.QLineEdit(self.findReplace)
        self.replaceText.setMinimumSize(QtCore.QSize(200, 0))
        self.replaceText.setObjectName("replaceText")
        self.horizontalLayout_3.addWidget(self.replaceText)
        self.replaceButton = QtWidgets.QPushButton(self.findReplace)
        self.replaceButton.setObjectName("replaceButton")
        self.horizontalLayout_3.addWidget(self.replaceButton)
        self.replaceAllButton = QtWidgets.QPushButton(self.findReplace)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.horizontalLayout_3.addWidget(self.replaceAllButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.findReplaceLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.findReplace)
        self.code = MyScintilla(CodeEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.code.sizePolicy().hasHeightForWidth())
        self.code.setSizePolicy(sizePolicy)
        self.code.setObjectName("code")
        self.verticalLayout_3.addWidget(self.code)

        self.retranslateUi(CodeEditor)
        QtCore.QMetaObject.connectSlotsByName(CodeEditor)

    def retranslateUi(self, CodeEditor):
        _translate = QtCore.QCoreApplication.translate
        self.findButton.setText(_translate("CodeEditor", "Next"))
        self.findPrevButton.setText(_translate("CodeEditor", "Previous"))
        self.replaceButton.setText(_translate("CodeEditor", "Replace"))
        self.replaceAllButton.setText(_translate("CodeEditor", "Replace All"))
from ui.widgets.shared.my_scintilla import MyScintilla
