# Form implementation generated from reading ui file 'src/views/shared/headers_form.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HeadersForm(object):
    def setupUi(self, HeadersForm):
        HeadersForm.setObjectName("HeadersForm")
        HeadersForm.resize(880, 521)
        self.verticalLayout = QtWidgets.QVBoxLayout(HeadersForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLine = QtWidgets.QLineEdit(HeadersForm)
        self.headerLine.setObjectName("headerLine")
        self.verticalLayout.addWidget(self.headerLine)
        self.headersTable = QtWidgets.QTableView(HeadersForm)
        self.headersTable.setObjectName("headersTable")
        self.verticalLayout.addWidget(self.headersTable)

        self.retranslateUi(HeadersForm)
        QtCore.QMetaObject.connectSlotsByName(HeadersForm)

    def retranslateUi(self, HeadersForm):
        pass
