# Form implementation generated from reading ui file 'src/ui/views/shared/variables_popup.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VariablesPopup(object):
    def setupUi(self, VariablesPopup):
        VariablesPopup.setObjectName("VariablesPopup")
        VariablesPopup.resize(485, 313)
        self.verticalLayout = QtWidgets.QVBoxLayout(VariablesPopup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(VariablesPopup)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.varsTable = HoverableQTableView(VariablesPopup)
        self.varsTable.setObjectName("varsTable")
        self.verticalLayout.addWidget(self.varsTable)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(VariablesPopup)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.saveButton = QtWidgets.QPushButton(VariablesPopup)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_5.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(VariablesPopup)
        QtCore.QMetaObject.connectSlotsByName(VariablesPopup)

    def retranslateUi(self, VariablesPopup):
        _translate = QtCore.QCoreApplication.translate
        VariablesPopup.setWindowTitle(_translate("VariablesPopup", "Global Variables"))
        self.label.setText(_translate("VariablesPopup", "Global Variables are available in all requests and in the interceptor."))
        self.cancelButton.setText(_translate("VariablesPopup", "Cancel"))
        self.saveButton.setText(_translate("VariablesPopup", "Save"))
from ui.widgets.qt.hoverable_q_table_view import HoverableQTableView
