version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      #- run: sudo apt install libnss3 libxcomposite-dev libxrandr2 libxi6 libxtst6 libasound2 libxcursor1 qt5-default
      - run:
          command: PYTHONPATH="./src:./test" python -m pytest -s ./test/unit
          name: Unit Tests

      - run:
          command: PYTHONPATH="./src:./test" python -m pytest -s ./test/integration
          name: Integration Tests

workflows:
  main:
    jobs:
      - build-and-test
