version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: dev-requirements.txt
      - run: sudo apt-get update && sudo apt install libnss3 libxcomposite-dev libxrandr2 libxi6 libxtst6 libasound2 libxcursor1 libxdamage1 qt5-default x11-utils xvfb
      #- run: sudo apt-get update && sudo apt install libglapi-mesa libxcb-glx0 libxxf86vm1 libxdamage1 libxcursor1
      - run:
          command: PYTHONPATH="./src:./test:./src/proxy" python -m pytest -s ./test/unit
          name: Unit Tests

      - run:
          command: QT_DEBUG_PLUGINS=1 PYTHONPATH="./src:./test:./src/proxy" xvfb-run python -m pytest -s ./test/integration
          name: Integration Tests

workflows:
  main:
    jobs:
      - build-and-test
