# Form implementation generated from reading ui file 'src/views/shared/code_editor.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CodeEditor(object):
    def setupUi(self, CodeEditor):
        CodeEditor.setObjectName("CodeEditor")
        CodeEditor.resize(880, 521)
        self.verticalLayout = QtWidgets.QVBoxLayout(CodeEditor)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.code = MyScintilla(CodeEditor)
        self.code.setObjectName("code")
        self.verticalLayout.addWidget(self.code)

        self.retranslateUi(CodeEditor)
        QtCore.QMetaObject.connectSlotsByName(CodeEditor)

    def retranslateUi(self, CodeEditor):
        pass
from widgets.shared.my_scintilla import MyScintilla
