# Form implementation generated from reading ui file 'src/views/network/http_page.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HttpPage(object):
    def setupUi(self, HttpPage):
        HttpPage.setObjectName("HttpPage")
        HttpPage.resize(1400, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(HttpPage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pageToolbar = QtWidgets.QWidget(HttpPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageToolbar.sizePolicy().hasHeightForWidth())
        self.pageToolbar.setSizePolicy(sizePolicy)
        self.pageToolbar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pageToolbar.setObjectName("pageToolbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pageToolbar)
        self.horizontalLayout.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.pageToolbar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toggleButton = QtWidgets.QPushButton(self.pageToolbar)
        self.toggleButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.toggleButton.setObjectName("toggleButton")
        self.horizontalLayout.addWidget(self.toggleButton)
        self.verticalLayout.addWidget(self.pageToolbar)
        self.requestsTableAndViewSplitter = QtWidgets.QSplitter(HttpPage)
        self.requestsTableAndViewSplitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.requestsTableAndViewSplitter.setObjectName("requestsTableAndViewSplitter")
        self.tableAndSiteMapSplitter = QtWidgets.QSplitter(self.requestsTableAndViewSplitter)
        self.tableAndSiteMapSplitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.tableAndSiteMapSplitter.setObjectName("tableAndSiteMapSplitter")
        self.siteMap = ItemExplorer(self.tableAndSiteMapSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.siteMap.sizePolicy().hasHeightForWidth())
        self.siteMap.setSizePolicy(sizePolicy)
        self.siteMap.setMinimumSize(QtCore.QSize(125, 0))
        self.siteMap.setObjectName("siteMap")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tableAndSiteMapSplitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.requestsTableWidget = RequestsTable()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requestsTableWidget.sizePolicy().hasHeightForWidth())
        self.requestsTableWidget.setSizePolicy(sizePolicy)
        self.requestsTableWidget.setMinimumSize(QtCore.QSize(650, 0))
        self.requestsTableWidget.setObjectName("requestsTableWidget")
        self.stackedWidget.addWidget(self.requestsTableWidget)
        self.loaderWidget = Loader()
        self.loaderWidget.setObjectName("loaderWidget")
        self.stackedWidget.addWidget(self.loaderWidget)
        self.requestViewWidget = FlowView(self.requestsTableAndViewSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requestViewWidget.sizePolicy().hasHeightForWidth())
        self.requestViewWidget.setSizePolicy(sizePolicy)
        self.requestViewWidget.setObjectName("requestViewWidget")
        self.verticalLayout.addWidget(self.requestsTableAndViewSplitter)

        self.retranslateUi(HttpPage)
        QtCore.QMetaObject.connectSlotsByName(HttpPage)

    def retranslateUi(self, HttpPage):
        _translate = QtCore.QCoreApplication.translate
        HttpPage.setWindowTitle(_translate("HttpPage", "Form"))
        self.label.setText(_translate("HttpPage", "NETWORK - HTTP"))
        self.toggleButton.setText(_translate("HttpPage", "WEBSOCKET"))
from ui.widgets.editor.item_explorer import ItemExplorer
from ui.widgets.network.http.requests_table import RequestsTable
from ui.widgets.shared.flow_view import FlowView
from ui.widgets.shared.loader import Loader
