# Form implementation generated from reading ui file 'src/views/network/ws/message_view.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MessageView(object):
    def setupUi(self, MessageView):
        MessageView.setObjectName("MessageView")
        MessageView.resize(590, 678)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MessageView)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(MessageView)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.messageTabs = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageTabs.sizePolicy().hasHeightForWidth())
        self.messageTabs.setSizePolicy(sizePolicy)
        self.messageTabs.setObjectName("messageTabs")
        self.messageTab = QtWidgets.QWidget()
        self.messageTab.setObjectName("messageTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.messageTab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.messageText = QtWidgets.QPlainTextEdit(self.messageTab)
        self.messageText.setObjectName("messageText")
        self.verticalLayout_4.addWidget(self.messageText)
        self.messageTabs.addTab(self.messageTab, "")
        self.messageModifiedTab = QtWidgets.QWidget()
        self.messageModifiedTab.setEnabled(True)
        self.messageModifiedTab.setObjectName("messageModifiedTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.messageModifiedTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.messageModifiedText = QtWidgets.QPlainTextEdit(self.messageModifiedTab)
        self.messageModifiedText.setObjectName("messageModifiedText")
        self.verticalLayout_3.addWidget(self.messageModifiedText)
        self.messageTabs.addTab(self.messageModifiedTab, "")
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(MessageView)
        self.messageTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MessageView)

    def retranslateUi(self, MessageView):
        _translate = QtCore.QCoreApplication.translate
        MessageView.setWindowTitle(_translate("MessageView", "Form"))
        self.messageTabs.setTabText(self.messageTabs.indexOf(self.messageTab), _translate("MessageView", "Message"))
        self.messageTabs.setTabText(self.messageTabs.indexOf(self.messageModifiedTab), _translate("MessageView", "(Modified)"))
