# Form implementation generated from reading ui file 'src/views/graphics_page.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GraphicsPage(object):
    def setupUi(self, GraphicsPage):
        GraphicsPage.setObjectName("GraphicsPage")
        GraphicsPage.resize(897, 581)
        self.horizontalLayout = QtWidgets.QHBoxLayout(GraphicsPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(GraphicsPage)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)

        self.retranslateUi(GraphicsPage)
        QtCore.QMetaObject.connectSlotsByName(GraphicsPage)

    def retranslateUi(self, GraphicsPage):
        _translate = QtCore.QCoreApplication.translate
        GraphicsPage.setWindowTitle(_translate("GraphicsPage", "Form"))
