# Form implementation generated from reading ui file 'src/ui/views/editor/examples_table.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExamplesTable(object):
    def setupUi(self, ExamplesTable):
        ExamplesTable.setObjectName("ExamplesTable")
        ExamplesTable.resize(424, 702)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExamplesTable.sizePolicy().hasHeightForWidth())
        ExamplesTable.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ExamplesTable)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ExamplesTable)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableView(ExamplesTable)
        self.table.setObjectName("table")
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ExamplesTable)
        QtCore.QMetaObject.connectSlotsByName(ExamplesTable)

    def retranslateUi(self, ExamplesTable):
        _translate = QtCore.QCoreApplication.translate
        ExamplesTable.setWindowTitle(_translate("ExamplesTable", "Form"))
        self.label.setText(_translate("ExamplesTable", "Saved Examples"))
