# Form implementation generated from reading ui file 'src/ui/views/docker/docker_tab.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DockerTab(object):
    def setupUi(self, DockerTab):
        DockerTab.setObjectName("DockerTab")
        DockerTab.resize(725, 625)
        self.verticalLayout = QtWidgets.QVBoxLayout(DockerTab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dockerViewSplitter = QtWidgets.QSplitter(DockerTab)
        self.dockerViewSplitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.dockerViewSplitter.setObjectName("dockerViewSplitter")
        self.responseStackedWidget = QtWidgets.QStackedWidget(self.dockerViewSplitter)
        self.responseStackedWidget.setObjectName("responseStackedWidget")
        self.dockerContainerTabs = QtWidgets.QTabWidget()
        self.dockerContainerTabs.setObjectName("dockerContainerTabs")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_6_body = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_6_body.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6_body.setObjectName("verticalLayout_6_body")
        self.containerText = QtWidgets.QPlainTextEdit(self.tab_1)
        self.containerText.setReadOnly(True)
        self.containerText.setObjectName("containerText")
        self.verticalLayout_6_body.addWidget(self.containerText)
        self.dockerContainerTabs.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6_body1 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6_body1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6_body1.setObjectName("verticalLayout_6_body1")
        self.networkText = QtWidgets.QPlainTextEdit(self.tab_2)
        self.networkText.setReadOnly(True)
        self.networkText.setObjectName("networkText")
        self.verticalLayout_6_body1.addWidget(self.networkText)
        self.dockerContainerTabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6_body2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6_body2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6_body2.setObjectName("verticalLayout_6_body2")
        self.logsText = QtWidgets.QPlainTextEdit(self.tab_3)
        self.logsText.setReadOnly(True)
        self.logsText.setObjectName("logsText")
        self.verticalLayout_6_body2.addWidget(self.logsText)
        self.dockerContainerTabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7_body = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7_body.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7_body.setObjectName("verticalLayout_7_body")
        self.consoleText = ConsoleScintilla(self.tab_4)
        self.consoleText.setObjectName("consoleText")
        self.verticalLayout_7_body.addWidget(self.consoleText)
        self.dockerContainerTabs.addTab(self.tab_4, "")
        self.responseStackedWidget.addWidget(self.dockerContainerTabs)
        self.verticalLayout.addWidget(self.dockerViewSplitter)

        self.retranslateUi(DockerTab)
        self.dockerContainerTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockerTab)

    def retranslateUi(self, DockerTab):
        _translate = QtCore.QCoreApplication.translate
        self.dockerContainerTabs.setTabText(self.dockerContainerTabs.indexOf(self.tab_1), _translate("DockerTab", "Container"))
        self.dockerContainerTabs.setTabText(self.dockerContainerTabs.indexOf(self.tab_2), _translate("DockerTab", "Network"))
        self.dockerContainerTabs.setTabText(self.dockerContainerTabs.indexOf(self.tab_3), _translate("DockerTab", "Logs"))
        self.dockerContainerTabs.setTabText(self.dockerContainerTabs.indexOf(self.tab_4), _translate("DockerTab", "Console"))
from ui.widgets.docker.console_scintilla import ConsoleScintilla
